-- Wurzburg Oracle foundation schema.
-- IDs are generated by Wurzburg as UUIDs and stored as RAW(16).

CREATE TABLE schema_migrations (
    version VARCHAR2(64) PRIMARY KEY,
    description VARCHAR2(255) NOT NULL,
    checksum VARCHAR2(128) NOT NULL,
    applied_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE idempotency_records (
    id RAW(16) PRIMARY KEY,
    operation_type VARCHAR2(100) NOT NULL,
    idempotency_key VARCHAR2(255) NOT NULL,
    request_hash VARCHAR2(128) NOT NULL,
    status VARCHAR2(32) NOT NULL,
    resource_type VARCHAR2(100),
    resource_id RAW(16),
    response_snapshot JSON,
    error_snapshot JSON,
    created_by_subject VARCHAR2(255) NOT NULL,
    created_by_client_id VARCHAR2(255),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uq_idempotency_operation_key UNIQUE (operation_type, idempotency_key),
    CONSTRAINT ck_idempotency_status CHECK (
        status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED', 'CONFLICT')
    )
);

CREATE TABLE providers (
    id RAW(16) PRIMARY KEY,
    legal_name VARCHAR2(255) NOT NULL,
    trade_name VARCHAR2(255) NOT NULL,
    tax_id VARCHAR2(64) NOT NULL,
    email_address VARCHAR2(255) NOT NULL,
    office_phone VARCHAR2(64) NOT NULL,
    website_url VARCHAR2(512),
    mailing_address VARCHAR2(1000) NOT NULL,
    alert_phone_numbers JSON,
    status VARCHAR2(32) NOT NULL,
    operational_metadata JSON,
    created_by_subject VARCHAR2(255) NOT NULL,
    updated_by_subject VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_providers_tax_id UNIQUE (tax_id),
    CONSTRAINT ck_providers_status CHECK (
        status IN ('DRAFT', 'ACTIVE', 'SUSPENDED', 'INACTIVE')
    )
);

CREATE TABLE provider_ledger_accounts (
    id RAW(16) PRIMARY KEY,
    provider_id RAW(16) NOT NULL,
    account_category VARCHAR2(32) NOT NULL,
    tigerbeetle_account_id RAW(16) NOT NULL,
    status VARCHAR2(32) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_provider_ledger_provider
        FOREIGN KEY (provider_id) REFERENCES providers(id),
    CONSTRAINT uq_provider_ledger_account UNIQUE (tigerbeetle_account_id),
    CONSTRAINT uq_provider_ledger_category UNIQUE (provider_id, account_category),
    CONSTRAINT ck_provider_ledger_category CHECK (
        account_category IN ('PROVIDER_OWNED', 'CMS_SETTLEMENT', 'PLATFORM_FEE')
    ),
    CONSTRAINT ck_provider_ledger_status CHECK (
        status IN ('PENDING_PROVISIONING', 'ACTIVE', 'SUSPENDED', 'FAILED')
    )
);

CREATE TABLE business_config (
    config_key VARCHAR2(255) PRIMARY KEY,
    value_json JSON NOT NULL,
    value_type VARCHAR2(64) NOT NULL,
    version NUMBER(19,0) NOT NULL,
    status VARCHAR2(32) NOT NULL,
    effective_at TIMESTAMP(6) WITH TIME ZONE,
    updated_by_subject VARCHAR2(255) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    description VARCHAR2(1000),
    CONSTRAINT ck_business_config_status CHECK (
        status IN ('DRAFT', 'ACTIVE', 'SUSPENDED')
    )
);

CREATE TABLE business_config_audit (
    id RAW(16) PRIMARY KEY,
    config_key VARCHAR2(255) NOT NULL,
    old_value_json JSON,
    new_value_json JSON,
    old_version NUMBER(19,0),
    new_version NUMBER(19,0) NOT NULL,
    changed_by_subject VARCHAR2(255) NOT NULL,
    changed_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    reason VARCHAR2(1000),
    CONSTRAINT fk_business_config_audit_key
        FOREIGN KEY (config_key) REFERENCES business_config(config_key)
);

CREATE TABLE audit_logs (
    id RAW(16) PRIMARY KEY,
    entity_type VARCHAR2(100) NOT NULL,
    entity_id RAW(16) NOT NULL,
    action_type VARCHAR2(32) NOT NULL,
    old_values JSON,
    new_values JSON,
    actor_subject VARCHAR2(255) NOT NULL,
    actor_client_id VARCHAR2(255),
    actor_provider_id RAW(16),
    correlation_id VARCHAR2(128) NOT NULL,
    request_id VARCHAR2(128),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_audit_action CHECK (
        action_type IN ('INSERT', 'UPDATE', 'DELETE', 'STATE_TRANSITION')
    )
);

CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_correlation ON audit_logs(correlation_id);
CREATE INDEX idx_idempotency_resource ON idempotency_records(resource_type, resource_id);
