use axum::{
    Router, middleware,
    routing::{get, post},
};
use std::sync::Arc;

use super::handlers::{
    audit_logs, card_issuance, card_policies, card_ranges, cards, financial_transactions,
    provider_credits, provider_events, provider_fees, provider_identity,
    provider_operational_profiles, provider_users, providers, system,
};
use crate::telemetry::http::trace_http_request;
use crate::{api::cors::manual_cors_middleware, state::AppState};

pub fn build_app_router(state: Arc<AppState>) -> Router {
    let token_transport = state.config.wso2.backend_token_transport;
    let system_routes = Router::new().route("/db-health", get(system::db_health));

    let api_router = Router::new()
        .route(
            "/providers/{provider_id}/transactions",
            get(financial_transactions::list_provider_transactions),
        )
        .route(
            "/providers/{provider_id}/users/{user_id}/transactions",
            get(financial_transactions::list_provider_user_transactions),
        )
        .route(
            "/providers/{provider_id}/cards/{card_number}/transactions",
            get(financial_transactions::list_provider_card_transactions),
        )
        .route(
            "/providers/{provider_id}/accounts/{account_category}/transactions",
            get(financial_transactions::list_provider_account_transactions),
        )
        .route(
            "/users/{user_id}/transactions",
            get(financial_transactions::list_cardholder_transactions),
        )
        .route(
            "/cards/{card_number}/transactions",
            get(financial_transactions::list_cardholder_card_transactions),
        )
        .route(
            "/admin/transactions",
            get(financial_transactions::list_admin_transactions),
        )
        .route(
            "/admin/cards/{card_number}/transactions",
            get(financial_transactions::list_admin_card_transactions),
        )
        .route(
            "/providers/{provider_id}/credits/grant",
            post(provider_credits::grant_credit),
        )
        .route(
            "/providers/{provider_id}/credits/return",
            post(provider_credits::return_provider_credit),
        )
        .route(
            "/providers/{provider_id}/users/{user_id}/credit",
            get(provider_credits::get_provider_user_credit),
        )
        .route(
            "/cards/{card_number}/providers/{provider_id}/credit",
            get(provider_credits::get_cardholder_credit),
        )
        .route(
            "/cards/{card_number}/providers/{provider_id}/credit/return",
            post(provider_credits::return_cardholder_credit),
        )
        .route(
            "/cards/{card_number}/funding-order",
            axum::routing::put(cards::update_funding_order),
        )
        .route(
            "/admin/card-issuance-batches",
            post(card_issuance::create_card_issuance_batch)
                .get(card_issuance::list_card_issuance_batches),
        )
        .route(
            "/admin/card-issuance-batches/{batch_id}",
            get(card_issuance::get_card_issuance_batch),
        )
        .route(
            "/admin/card-issuance-batches/{batch_id}/request-file",
            get(card_issuance::download_card_issuance_request_file),
        )
        .route(
            "/admin/card-issuance-batches/{batch_id}/result-file",
            post(card_issuance::upload_card_issuance_result_file),
        )
        .route(
            "/admin/card-issuance-batches/{batch_id}/result",
            get(card_issuance::get_card_issuance_batch_result),
        )
        .route(
            "/providers/{provider_id}/users",
            post(provider_users::enroll_provider_user).get(provider_users::list_provider_users),
        )
        .route(
            "/providers/{provider_id}/users/{user_id}",
            get(provider_users::get_provider_user),
        )
        .route(
            "/users/{user_id}/cards",
            get(provider_users::list_user_cards),
        )
        .route(
            "/users/{user_id}/providers",
            get(provider_users::list_user_providers),
        )
        .route(
            "/providers/{provider_id}/operational-profile",
            get(provider_operational_profiles::get_current_provider_operational_profile),
        )
        .route(
            "/providers/{provider_id}/operational-profiles",
            get(provider_operational_profiles::list_provider_operational_profiles)
                .post(provider_operational_profiles::set_provider_operational_profile),
        )
        .route(
            "/providers/{provider_id}/operational-profiles/{profile_id}/cancel",
            post(provider_operational_profiles::cancel_scheduled_provider_operational_profile),
        )
        .route(
            "/providers/{provider_id}/fee-profile",
            get(provider_fees::get_current_provider_fee_profile)
                .put(provider_fees::set_provider_fee_profile),
        )
        .route(
            "/providers/{provider_id}/fee-profiles",
            get(provider_fees::list_provider_fee_profiles),
        )
        .route(
            "/providers/{provider_id}/fee-profiles/{fee_profile_id}",
            get(provider_fees::get_provider_fee_profile),
        )
        .route(
            "/providers",
            post(providers::create_provider).get(providers::list_providers),
        )
        .route(
            "/providers/{provider_id}",
            get(providers::get_provider).patch(provider_identity::update_provider_identity),
        )
        .route(
            "/providers/{provider_id}/contacts",
            get(provider_identity::list_provider_contacts)
                .post(provider_identity::create_provider_contact),
        )
        .route(
            "/providers/{provider_id}/contacts/{contact_id}",
            axum::routing::patch(provider_identity::update_provider_contact),
        )
        .route(
            "/providers/{provider_id}/contacts/{contact_id}/suspend",
            post(provider_identity::suspend_provider_contact),
        )
        .route(
            "/providers/{provider_id}/contacts/{contact_id}/reactivate",
            post(provider_identity::reactivate_provider_contact),
        )
        .route(
            "/providers/{provider_id}/ledger",
            get(providers::get_provider_ledger),
        )
        .route("/admin/audit-logs", get(audit_logs::list_audit_logs))
        .route(
            "/providers/{provider_id}/kafka/credentials",
            get(providers::get_provider_kafka_credentials),
        )
        .route(
            "/providers/{provider_id}/kafka/status",
            get(providers::get_provider_kafka_status),
        )
        .route(
            "/providers/{provider_id}/kafka/provision",
            post(providers::provision_provider_kafka),
        )
        .route(
            "/providers/{provider_id}/kafka/rotate-credentials",
            post(providers::rotate_provider_kafka_credentials),
        )
        .route(
            "/providers/{provider_id}/kafka/suspend",
            post(providers::suspend_provider_kafka),
        )
        .route(
            "/providers/{provider_id}/kafka/resume",
            post(providers::resume_provider_kafka),
        )
        .route(
            "/providers/kafka/certificate",
            get(providers::get_provider_kafka_certificate),
        )
        .route(
            "/providers/{provider_id}/event-subscriptions",
            get(provider_events::get_provider_event_subscriptions),
        )
        .route(
            "/admin/provider-event-types",
            get(provider_events::list_provider_event_types),
        )
        .route(
            "/admin/provider-event-types/{event_type}/schemas/{schema_version}",
            get(provider_events::get_provider_event_contract),
        )
        .route(
            "/admin/providers/{provider_id}/event-subscriptions",
            get(provider_events::get_admin_provider_event_subscriptions)
                .put(provider_events::replace_provider_event_subscriptions),
        )
        .route(
            "/providers/{provider_id}/card-range",
            axum::routing::put(providers::assign_provider_card_range),
        )
        .route(
            "/providers/{provider_id}/activate",
            post(providers::activate_provider),
        )
        .route(
            "/providers/{provider_id}/suspend",
            post(providers::suspend_provider),
        )
        .route(
            "/providers/{provider_id}/deactivate",
            post(providers::deactivate_provider),
        )
        .route(
            "/card-ranges",
            post(card_ranges::create_card_range).get(card_ranges::list_card_ranges),
        )
        .route(
            "/card-ranges/{card_range_id}",
            get(card_ranges::get_card_range).patch(card_ranges::update_draft_card_range),
        )
        .route(
            "/card-ranges/{card_range_id}/activate",
            post(card_ranges::activate_card_range),
        )
        .route(
            "/card-ranges/{card_range_id}/suspend",
            post(card_ranges::suspend_card_range),
        )
        .route(
            "/card-ranges/{card_range_id}/operational-controls",
            axum::routing::put(card_ranges::update_card_range_controls),
        )
        .route(
            "/card-ranges/{card_range_id}/providers",
            get(card_ranges::list_card_range_providers),
        )
        .route(
            "/operations/{operation_id}",
            get(card_ranges::get_integration_operation),
        )
        .route(
            "/card-ranges/{card_range_id}/policy",
            get(card_policies::get_current_card_policy).put(card_policies::set_card_policy),
        )
        .route(
            "/card-ranges/{card_range_id}/policies",
            get(card_policies::list_card_policies),
        )
        .route(
            "/card-ranges/{card_range_id}/policies/{policy_id}",
            get(card_policies::get_card_policy),
        )
        .nest("/system", system_routes);

    Router::new()
        .route("/ping", get(|| async { "pong" }))
        .nest("/api/v1", api_router)
        .with_state(state)
        .layer(middleware::from_fn_with_state(
            token_transport,
            trace_http_request,
        ))
        .layer(axum::middleware::from_fn(manual_cors_middleware))
}
